

package com.ounis.utils;

import static java.lang.String.format;




/**
 *
 * @author AndroidAppsPlatform
 */
public class HTMLTags {

    // HTML RESERVED CHARS
    public static final String RCHAR_QUOT = "&quot;";  //"
    public static final String RCHAR_APOS = "&apos;";  //'
    public static final String RCHAR_AMP = "&amp;";     //&
    public static final String RCHAR_LT = "&lt;"; // <
    public static final String RCHAR_GT = "&gt;"; // >
    public static final String RCHAR_SPACE = "&nbsp;"; // 
                  
    
    // HTML TAGS
    
    private static final String HTML_TAG_HTML_OPEN = "<html %s>";
    private static final String HTML_TAG_HTML_CLOSE= "</html>";
    
    private static final String HTML_TAG_BODY_OPEN = "<body %s>";
    private static final String HTML_TAG_BODY_CLOSE = "</body>";
    
    private static final String HTML_TAG_HEAD_OPEN = "<head %s>";
    private static final String HTML_TAG_HEAD_CLOSE = "</head>";
    
    private static final String HTML_TAG_LINK = "<link %s/>";
    
    private static final String HTML_TAG_TITLE = "<title>%s</title>";
    
    private static final String HTML_TAG_P_OPEN = "<p>";
    private static final String HTML_TAG_P_CLOSE ="</p>";
    
    private static final String HTML_TAG_BR = "<br>";
    
    private static final String HTML_TAG_H2_OPEN = "<h2>";
    private static final String HTML_TAG_H2_CLOSE = "</h2>";
    private static final String HTML_TAG_H2 = HTML_TAG_H2_OPEN + "%s" + HTML_TAG_H2_CLOSE;
    
    private static final String HTML_TAG_B_OPEN = "<b>";
    private static final String HTML_TAG_B_CLOSE = "</b>";
    private static final String HTML_TAG_B = HTML_TAG_B_OPEN + "%s" + HTML_TAG_B_CLOSE;
    
    private static final String HTML_TAG_A = "<a href=\"%s\">%s</a>";
    
    private static final String HTML_TAG_IMG = "<img src=\"%s\" alt=\"%s\"/>";
    
    //<font size="1">Generated by: # BIBLIOTECZKA v1.2, modul SLUCHOWISKA  2016-12-08 07:49:07 - written by OuNiS</font>
    private static final String HTML_TAG_FONT_SIZE = "<font size=\"%d\">%s</font>";
    private static final String HTML_TAG_FONT = "<font %s>%s</font>";
    
    private static final String HTML_TAG_HR = "<hr>";
    
    private static final String HTML_TAG_REM_OPEN = "<!--";
    private static final String HTML_TAG_REM_CLOSE = "-->";
    private static final String HTML_TAG_REM = HTML_TAG_REM_OPEN + "%s" + HTML_TAG_REM_CLOSE;
    
    private static final String HTML_TAG_TABLE_OPEN = "<table %s>";
    private static final String HTML_TAG_TABLE_CLOSE = "</table>";
    private static final String HTML_TAG_TR_OPEN = "<tr %s>";
    private static final String HTML_TAG_TR_CLOSE = "</tr>";
    private static final String HTML_TAG_TR = HTML_TAG_TR_OPEN + "%s" + HTML_TAG_TR_CLOSE;
    private static final String HTML_TAG_TD_OPEN = "<td %s>";
    private static final String HTML_TAG_TD_CLOSE = "</td>";
    private static final String HTML_TAG_TD = HTML_TAG_TD_OPEN + "%s" + HTML_TAG_TD_CLOSE;
    private static final String HTML_TAG_TH_OPEN = "<th %s>";
    private static final String HTML_TAG_TH_CLOSE = "</th>";
    private static final String HTML_TAG_TH = HTML_TAG_TH_OPEN + "%s" + HTML_TAG_TH_CLOSE;
    
    public String getHTMLOPEN() {
        return getHTMLOPEN("");
    }
    public String getHTMLOPEN(String aParams) {
        return String.format(HTML_TAG_HTML_OPEN, aParams);
    }
    
    public String getHTMLCLOSE() {
        return HTML_TAG_HTML_CLOSE;
    }
    
    public String getHEADOPEN() {
        return getHEADOPEN("");
    }
    public String getHEADOPEN(String aParams) {
        return String.format(HTML_TAG_HEAD_OPEN, aParams);
    }
    
    public String getHEADCLOSE() {
        return HTML_TAG_HEAD_CLOSE;
    }
    
    public String getLINK(String aParams) {
        return String.format(HTML_TAG_LINK, aParams);
    }
    
    public String getTITLE(String aParams) {
        return String.format(HTML_TAG_TITLE, aParams);
    }
    
    public String getBODYOPEN() {
        return getBODYOPEN("");
    }
    public String getBODYOPEN(String aParams) {
        return String.format(HTML_TAG_BODY_OPEN, aParams);
    }
    
    public String getBODYCLOSE() {
        return HTML_TAG_BODY_CLOSE;
    }
    
    public String getPO(){
        return HTML_TAG_P_OPEN;
    }
    
    public String getPC(){
        return HTML_TAG_P_CLOSE;
    }
    
    public String getBR() {
        return HTML_TAG_BR;
    }
    
    public String getH2O() {
        return HTML_TAG_H2_OPEN;
    }
    
    public String getH2C() {
        return HTML_TAG_H2_CLOSE;
    }
    
    public String getH2(String aValue){
        return String.format(HTML_TAG_H2, aValue);
    }
    
    public String getBO() {
        return HTML_TAG_B_OPEN;
    }
    
    public String getBC() {
        return HTML_TAG_B_CLOSE;
    }
    
    public String getB(String aValue) {
        return String.format(HTML_TAG_B, aValue);
    }
    
    public String getA(String aLink, String aText){
        return String.format(HTML_TAG_A, aLink, aText);
    }
    
    public String getIMG(String imgLink, String aAltText){
        return String.format(HTML_TAG_IMG, imgLink, aAltText);
    }
    
    public String getFont(int fontSize, String aText){
        return String.format(HTML_TAG_FONT_SIZE, fontSize, aText);
    }
    
    public String getFont(String aParams, String aText) {
        return String.format(HTML_TAG_FONT, aParams, aText);
    }
    
    public String getHR() {
        return HTML_TAG_HR;
    }
    
    public String getREMO() {
        return HTML_TAG_REM_OPEN;
    }
    
    public String getREMC() {
        return HTML_TAG_REM_CLOSE;
    }
    
    public String getREM(String aValue) {
        return String.format(HTML_TAG_REM, aValue);
    }

    // Table
    public String getTABLEO(String aParams) {
        return String.format(HTML_TAG_TABLE_OPEN, aParams);
    }
    
    public String getTABLEC() {
        return HTML_TAG_TABLE_CLOSE;
    }
    
    public String getTRO(String aParams) {
        return String.format(HTML_TAG_TR_OPEN, aParams);
    }
    
    public String getTRC() {
        return HTML_TAG_TR_CLOSE;
    }
    
    public String getTR(String aParams, String aValue) {
        return String.format(HTML_TAG_TR, aParams, aValue);
    }
    
    public String getTDO(String aParams) {
        return String.format(HTML_TAG_TD_OPEN, aParams);
    }
    
    public String getTDC() {
        return HTML_TAG_TD_CLOSE;
    }
    
    public String getTD(String aParams, String aValue) {
        return String.format(HTML_TAG_TD, aParams, aValue);
    }
    
    public String getTHO(String aParams) {
        return String.format(HTML_TAG_TH_OPEN, aParams);
    }
    
    public String getTHC() {
        return HTML_TAG_TH_CLOSE;
    }
    
    public String getTH(String aParams, String aValue) {
        return String.format(HTML_TAG_TH, aParams, aValue);
    }
}
