/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ounis.utils;

import java.awt.Frame;
import java.awt.Component;
import javax.swing.JDialog;
import javax.swing.SwingUtilities;

/**
 *
 * @author AndroidAppsPlatform
 */
public abstract class ModalForm extends javax.swing.JPanel {

    // element wyœwietlaj¹cy panel i umo¿liwiaj¹cy modalnoœæ
    protected JDialog dialog;
    
    // pole result do wykorzystania w sterowaniu przebiegiem
    protected boolean result;
    public boolean getResult() {
        return result;
    }
    
    /**
     * konstruktor formy ModalForm
     */
    public ModalForm() {
        initComponents();
    }

    /**
     * abstrakcyjna metoda umo¿liwiaj¹ca zmianê ustawieñ pola dialog
     * wywo³ywana w metodzie showModal()
     * @param aDialog - dialog który ma byæ konfigurowany w klasie potomnej
     */
    abstract protected void setDialogPrefs();
    
     /**
     * Wyœwietla dialog dialog box z przypiêtym panelem emuluj¹c formularz modalny
     * @param aParent - wskaŸnik obiektu, który wywo³a³ okno modalne
     */
    public void showModal(Component aParent) {
        
        Frame owner = null;
        if (aParent instanceof Frame)
            owner = (Frame) aParent;
        else
            owner = (Frame) SwingUtilities.getAncestorOfClass(Frame.class, aParent);
        
        if (dialog == null || dialog.getOwner() != owner)
          {
             dialog = new JDialog(owner, true);
             dialog.add(this);
             // domyœlny przycisk zamykania (opcjonalne)
             //dialog.getRootPane().setDefaultButton(btnClose);
             dialog.pack();
          }
        setDialogPrefs();

        dialog.setVisible(true);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
